version: '3'
services:
  builder:
    container_name: maven6
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql


  runner:
    container_name: tomcat6
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - builder
      - mysql
    ports:
      - "9080:8080"

  mysql:
    container_name: db2
    image: mysql
    ports:
      - "9935:5432"
    expose:
      - "5432"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure









