version: '3'
services:
  builder:
    container_name: maven5
    build:
      context: ./
      dockerfile: Dockerfile
  ports:
    - "8096:8080"


  runner:
    container_name: tomcat5
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8095:8080"

  mysql:
    container_name: db
    image: mysql
    ports:
      - "9935:5432"
    expose:
      - "5432"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql:/var/lib/mysql









