version: '3'
services:
  builder:
    container_name: maven3
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - runner
    ports:
      - "8082:8080"

  mysql:
    container_name: db
    image: mysql
    ports:
      - "9935:5432"
    expose:
      - "5432"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql:/vat/lib/mysql


  runner:
    container_name: tomcat3
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
    links:
      - mysql








