version: '3'
services:
  builder:
    container_name: maven
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  mysql:
    image: mysql
    ports:
      - "9934:5432"
    expose:
      - "5432"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql:/vat/lib/mysql


  runner:
    container_name: tomcat
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - "mysql"







