version: '3'
services:
  builder:
    container_name: maven
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:8080"

  mysql:
    image: mysql
    ports:
      - "9932:5432"
    expose:
      - "5432"
    environment:
      - MYSQL_ROOT_PASSWORD=pass


  runner:
    container_name: tomcat
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8031:8080"







